[DEFAULT]
debug = false

[openstack]
##### 环境变量文件
env = ''
##### 镜像ID
image_id = ''
##### 规格ID
flavor = ''

##### 创建虚拟机使用的网络ID列表
# net_ids = 

##### 挂载网卡使用的网络ID
# attach_net =

#### 是否使用云盘
# boot_from_volume = false

##### 指定AZ创建云主机， 例如 nova:hostA
# boot_az = false
##### 卷大小
# volume_size = 50

[scenario_test]
##### 总的任务数和并发任务数
# total = 1
# worker = 1

##### 指定需要测试的场景,
# 支持的操作：
#   stop, start, reboot
#   attach_interface, attach_interface_loop
#   attach_volume, attach_volume_loop
#   start, stop, reboot 
# 可以指定多个，例如 attach_interface:2 表示 <action 名>[:<数值>]

# scenarios =

##### 每次挂载网卡的个数
# attach_interface_nums_each_time = 1

##### 每次挂载卷的个数循环次数
# attach_volume_nums_each_time = 1
# attach_volume_loop_times = 2

##### 清理错误的虚拟机
# cleanup_error_vms = true

##### 允许检查 libvirt guest 内部 ip地址和block 设备
# enable_varify_guest_ip_address = false
# enable_varify_guest_ip_address = false

##### 跨设备热插拔的最少间隔
# device_toggle_min_interval = 4

[boot]
##### 创建虚拟机后，是否通过检查conole log 等待虚拟机完全启动
# check_console_log = False


[hard_reboot]
# times = 3
# interval = 10

