[DEFAULT]
debug = false

[openstack]
##### 环境变量文件
env = ''
##### 镜像ID
image_id = ''
##### 规格ID
flavor = ''

##### 创建虚拟机使用的网络ID列表
# net_ids = 

##### 挂载网卡使用的网络ID
# attach_net =

#### 是否使用云盘
# boot_from_volume = false

##### 指定AZ创建云主机， 例如 nova:hostA
# boot_az = false
##### 卷大小
# volume_size = 50

[ecs_test]
##### 总的任务数和并发任务数
# total = 1
# worker = 1

##### 指定需要测试的场景,
# 支持的操作：
#   stop, start, reboot
#   attach_interface, attach_interface_loop
#   attach_volume, attach_volume_loop
#   start, stop, reboot
#   extend_volume
#   live_migrate
# 可以指定多个，例如 attach_interface:2 表示 <action 名>[:<数值>]

# scenarios =

##### 每次挂载网卡的个数
# attach_interface_nums_each_time = 1

##### 每次挂载卷的个数循环次数
# attach_volume_nums_each_time = 1
# attach_volume_loop_times = 2

##### 清理错误的虚拟机
# cleanup_error_vms = true

##### 允许通过libvirt 连接 ECS 实例, 允许通过 QGA 命令
# enable_guest_connection = false
# enable_guest_qga_command = false

##### 允许检查 ECS console log
# enable_varify_console_log = false

##### 跨设备热插拔的最少间隔
# device_toggle_min_interval = 4