##### 日志级别
#  0: INFO
#  1: DEBUG
#  2: 更多日志
# verbose = 0
# debug = false
# log_file = 
# manager = 'openstack'

[openstack]
##### 认证信息
auth_url = 'http://keystone-server:35357/v3'
auth_username = ''
auth_password = ''
auth_project_name = ''

##### 镜像ID
image_id = ''
##### 规格ID, 第一个
flavors = ''

##### 创建虚拟机使用的网络ID列表
# net_ids = 

##### 挂载网卡使用的网络ID
# attach_net =

#### 是否使用云盘
# boot_from_volume = false

##### 指定AZ创建云主机， 例如 nova:hostA
# boot_az = false
##### 卷大小
# volume_size = 50

[ecs_test]
##### 总的任务数和并发任务数
# total = 1
# worker = 1

##### 指定需要测试的操作,
# 支持的操作：
#   rename,
#   stop, start, reboot
#   attach_interface, attach_interface_loop
#   attach_volume, attach_volume_loop
#   start, stop, reboot
#   extend_volume
#   live_migrate, migrate
# 可以指定多个，格式: <action 名>[:<次数>], 例如 attach_interface:3 表示测试三次挂载网卡

# actions =

##### 每次挂载网卡的个数
# attach_interface_nums_each_time = 1

##### 每次挂载卷的个数循环次数
# attach_volume_nums_each_time = 1
# attach_volume_loop_times = 2

##### 清理错误的虚拟机
# cleanup_error_vms = true

##### 允许通过libvirt 连接 ECS 实例, 允许通过 QGA 命令
# enable_guest_connection = false
# enable_guest_qga_command = false

##### 允许检查 ECS console log
# enable_varify_console_log = false

##### 跨设备热插拔的最少间隔
# device_toggle_min_interval = 4